# Generated by Django 5.2.7 on 2025-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='num_carte',
            field=models.CharField(default='NE000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
